// <auto-generated />
using System;
using MaktabShop.Infra.SqlServer.EFCore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaktabShop.Infra.SqlServer.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205113901_Seeddata")]
    partial class Seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core_MaktabShop.Domain.Core.CategoryAgg.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UptatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "مردانه"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "زنانه"
                        });
                });

            modelBuilder.Entity("Core_MaktabShop.Domain.Core.OrderAgg.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UptatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Core_MaktabShop.Domain.Core.OrderItemAgg.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UptatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("Core_MaktabShop.Domain.Core.ProductAgg.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UptatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "«هودی مشکی مردانه‌ای راحت و روزمره، با طراحی کلاهدار و فرم کلاسیک. مناسب برای روزهای خنک یا پاییز و زمستان، این هودی با ترکیب پنبه و پلی‌استر احساس نرم و گرم دارد. سبک اسپرت و شهری آن به‌راحتی با شلوار جین یا اسلش ست می‌شود.»",
                            ImageUrl = "/images/products/men-black-hoodie.jpg",
                            Name = "هودی مشکی مردانه",
                            Price = 2200000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "«کت چرم مشکی مردانه با طراحی کلاسیک و رسمی ـ نیمه‌رسمی. ساخته‌شده از چرم با کیفیت، این کت ظاهری شکیل و مقاوم دارد و برای استایل‌های شهری، رسمی‑کژوال یا شب مناسب است. ترکیب آن با شلوار جین یا کت‌وشلوار به هر دو استایل جلوه خاصی می‌دهد.»",
                            ImageUrl = "/images/products/men-black-leather-jacket.jpg",
                            Name = "کت چرم مشکی مردانه",
                            Price = 8890000m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "«سوییشرت خاکستری مردانه، سبک و راحت؛ انتخابی ایده‌آل برای استفاده روزمره و استایل‌های کژوال. با پارچه نرم و گرم، این سوییشرت مناسب فصل پاییز یا بهار خنک است و به راحتی با تی‌شرت و شلوار راحتی یا جین قابل ترکیب است.»",
                            ImageUrl = "/images/products/men-grey-sweatshirt.jpg",
                            Name = "سوییشرت خاکستری مردانه",
                            Price = 1990000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "«کت چرم زنانه مشکی با طراحی مدرن و شیک — ترکیب جذاب برای استایل کژوال یا خیابانی. این کت به‌واسطه فرم و رنگ مشکی با اکثر لباس‌ها ست می‌شود و برای فصل پاییز یا زمستان ـ با لایه‌بندی مناسب — انتخابی مطمئن است.»",
                            ImageUrl = "/images/products/women-black-leather-jacket.jpg",
                            Name = "کت چرم مشکی زنانه",
                            Price = 5750000m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "«کت جیر زنانه با رنگ قهوه‌ای گرم و طراحی کلاسیک، مناسب کسانی که دنبال ظاهری طبیعی، گرم و سبُک هستند. این کت برای روزهای خنک پاییز یا بهار مناسب است و با دامن، شلوار یا جین شکل‌های مختلفی می‌گیرد.»",
                            ImageUrl = "/images/products/women-brown-jacket.jpg",
                            Name = "کت جیر قهوه ای زنانه",
                            Price = 2790000m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "«کت سفید با بافت خز ـ انتخابی لوکس و خاص برای فصل سرما. این کت جلوه‌ی زمستانی دارد و می‌تواند نقطه تمرکز استایل شما باشد؛ مناسب برای مهمانی، بیرون رفتن یا خیابان‌گردی در هوای سرد.»",
                            ImageUrl = "/images/products/women-white-fur-coat.jpg",
                            Name = "کت خز سفید زنانه",
                            Price = 7750000m,
                            Stock = 5
                        });
                });

            modelBuilder.Entity("Core_MaktabShop.Domain.Core.UserAgg.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UptatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Wallet")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "تهران، شهرک غرب",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "غزل",
                            LastName = "مسیحا",
                            PasswordHash = "123456",
                            Phone = "09123456789",
                            Username = "ghazal",
                            Wallet = 10000000m
                        },
                        new
                        {
                            Id = 2,
                            Address = "رشت، گلسار",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "مرسده",
                            LastName = "کسروی",
                            PasswordHash = "123456",
                            Phone = "09111223344",
                            Username = "mersedeh",
                            Wallet = 7000000m
                        },
                        new
                        {
                            Id = 3,
                            Address = "تهران، پونک",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "امیر",
                            LastName = "ساعدی نیا",
                            PasswordHash = "123456",
                            Phone = "09111223343",
                            Username = "amir",
                            Wallet = 5000000m
                        });
                });

            modelBuilder.Entity("Core_MaktabShop.Domain.Core.OrderAgg.Entities.Order", b =>
                {
                    b.HasOne("Core_MaktabShop.Domain.Core.UserAgg.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core_MaktabShop.Domain.Core.OrderItemAgg.Entities.OrderItem", b =>
                {
                    b.HasOne("Core_MaktabShop.Domain.Core.OrderAgg.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core_MaktabShop.Domain.Core.ProductAgg.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core_MaktabShop.Domain.Core.ProductAgg.Entities.Product", b =>
                {
                    b.HasOne("Core_MaktabShop.Domain.Core.CategoryAgg.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core_MaktabShop.Domain.Core.CategoryAgg.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Core_MaktabShop.Domain.Core.OrderAgg.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Core_MaktabShop.Domain.Core.ProductAgg.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Core_MaktabShop.Domain.Core.UserAgg.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
